LIBRARY ieee ;
	USE ieee.std_logic_1164.all;
	USE ieee.std_logic_signed.all;

ENTITY ADDER IS
	PORT(	ENTRADA_0 	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
			ENTRADA_1	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
			RESULT 		: OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
	) ;
END ENTITY ; -- ADDER

ARCHITECTURE arch OF ADDER IS
BEGIN
	RESULT <= ENTRADA_0 + ENTRADA_1;
	
END ARCHITECTURE ; -- arch